version: '2'
services:

  # "app" would be your application server ...
  # could be configured as a backend of nginx ...
  # similar to how nginx is configured as a backend of varnish ...
  # here it is a simple node app 
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/var/nyt/app
      - /var/nyt/app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=*
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app
    links:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./app/public:/home/nginx/public
    restart: unless-stopped

  varnish:
    build:
      context: .
      dockerfile: ./varnish/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - nginx
    links:
      - nginx
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
    restart: unless-stopped
